home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.get_home.as_view(), name='home'),
    path('vehicles/', views.get_vehicles, name='vehicles'),
    path('services/', views.get_services, name='services'),
    path('featured/', views.get_featured, name='featured'),
    path('reviews/', views.get_reviews, name='reviews'),
    path('contact/', views.get_contact.as_view(), name='contact'),
    path('contactform/', views.get_contactForm.as_view(), name='contactform'),
    path('login/', views.get_login.as_view(), name='login'),
    path('register/', views.get_register.as_view(), name='register'),
    path('carselling/', views.get_car_selling, name='carselling'),
    path('repair/', views.get_parts_repair, name='repair'),
    path('insurance/', views.get_car_insurance, name='insurance'),
    path('battery/', views.get_battery, name='battery'),
    path('oilchange/', views.get_oil, name='oilchange'),
    path('support/', views.get_support, name='support'),
]   

projectcuoiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models

from django import forms

# Create your models here.
class contactforms(models.Model):
    fullname = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=50)
    message = models.TextField()
    def __str__(self):
        return self.fullname
    

home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .form import LoginForm, RegisterForm, form_contact
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import messages

# Create your views here.
class get_home(View):
    def get(self, request):
        cF = form_contact
        return render(request, 'home/home.html', {'cF':cF})
    def post(self, request):
        if request.method == "POST":
            cF = form_contact(request.POST)
        if cF.is_valid():
            cF.save()
            return HttpResponse("Save success!")
        else:
            return HttpResponse("not Post")

def get_vehicles(request):
    return render (request, 'home/vehicles.html')

def get_services(request):
    return render (request, 'home/services.html')

def get_featured(request):
    return render (request, 'home/featured.html')

def get_reviews(request):
    return render (request, 'home/reviews.html')

def get_car_selling(request):
    return render (request, 'home/car_selling.html')

def get_parts_repair(request):
    return render (request, 'home/repair.html')

def get_car_insurance(request):
    return render (request, 'home/car_insurance.html')

def get_battery(request):
    return render (request, 'home/battery.html')

def get_oil(request):
    return render (request, 'home/oil_change.html')

def get_support(request):
    return render (request, 'home/support.html')

class get_login(View):
    def get(self, request):
        lG = LoginForm
        return render(request, 'home/login.html', {'lG': lG})
    def post(self, request):
        username = request.POST['user_name']
        password = request.POST['password']
        user = authenticate(request, username = username, password=password)
        if user is not None: 
            login(request, user)
            return render(request, 'home/home1.html')
        else:
            messages.error(request, 'Đăng nhập không thành công. Vui lòng kiểm tra tên người dùng và mật khẩu.')
            return render(request, 'home/home.html')
    
class get_register(View):
    def get(self, request):
        rG = RegisterForm
        return render(request, 'home/register.html', {'rG': rG})
    def post(seft, request):
        username = request.POST['user_name']
        password = request.POST['password']
        c_password = request.POST['c_password']
        email = request.POST['email']
        if password == c_password:
            user = User.objects.create_user(username, email, password)
            user.save()
            return render (request , 'home/login.html')

        else:
            return HttpResponse('home/login.html')

class get_contact(View):
    def get(self, request):
        cF = form_contact
        return render(request, 'home/contact.html', {'cF':cF})
    def post(self, request):
        if request.method == "POST":
            cF = form_contact(request.POST)
        if cF.is_valid():
            cF.save()
            return HttpResponse("Save success!")
        else:
            return HttpResponse("not Post")
        
class get_contactForm(View):
    def post(self, request):
        if request.method == "POST":
            cF = form_contact(request.POST)
        if cF.is_valid():
            cF.save()
            return HttpResponse("Save success!")
        else:
            return HttpResponse("not Post")

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop Car Sports - {% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" type="text/css">

</head>

<body>

    <header class="header">

        <div id="menu-btn" class="fas fa-bars"></div>

        <a href="#" class="logo"> <span>max</span>wheels </a>

        <nav class="navbar">
            <a href={% url 'home:home' %}>home</a>
            <a href={% url 'home:vehicles' %}>vehicles</a>
            <a href={% url 'home:services' %}>services</a>
            <a href={% url 'home:featured' %}>featured</a>
            <a href={% url 'home:reviews' %}>reviews</a>
            <a href={% url 'home:contact' %}>contact</a>
        </nav>

        <div id="login-btn">
            <a href={% url 'home:login' %} class="btn">login</a>
            <i class="far fa-user"></i>
        </div>

    </header>

    <div class="login-form-container-none">

        <span id="close-login-form" class="fas fa-times"></span>

        <form action="">
            <h3>user login</h3>
            <input type="email" placeholder="email" class="box">
            <input type="password" placeholder="password" class="box">
            <p> forget your password <a href="#">click here</a> </p>
            <input type="submit" value="login" class="btn">
            <p>or login with</p>
            <div class="buttons">
                <a href="#" class="btn"> google </a>
                <a href="#" class="btn"> facebook </a>
            </div>
            <p> don't have an account <a href="#">create one</a> </p>
        </form>

    </div>

    <section class="home" id="home">

        <h3 data-speed="-2" class="home-parallax">find your car</h3>

        <img data-speed="5" class="home-parallax" src="{% static 'images/home-img.png' %}" alt="">

        <a data-speed="7" href="#" class="btn home-parallax">explore cars</a>

    </section>

    <section class="icons-container">

        <div class="icons">
            <i class="fas fa-home"></i>
            <div class="content">
                <h3>150+</h3>
                <p>branches</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-car"></i>
            <div class="content">
                <h3>4770+</h3>
                <p>cars sold</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-users"></i>
            <div class="content">
                <h3>320+</h3>
                <p>happy clients</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-car"></i>
            <div class="content">
                <h3>1500+</h3>
                <p>news cars</p>
            </div>
        </div>

    </section>

    {% block content %}{% endblock %}

    <section class="footer" id="footer">

        <div class="box-container">

            <div class="box">
                <h3>quick links</h3>
                <a href={% url 'home:home' %}> <i class="fas fa-arrow-right"></i> home </a>
                <a href={% url 'home:vehicles' %}> <i class="fas fa-arrow-right"></i> vehicles </a>
                <a href={% url 'home:services' %}> <i class="fas fa-arrow-right"></i> services </a>
                <a href={% url 'home:featured' %}> <i class="fas fa-arrow-right"></i> featured </a>
                <a href={% url 'home:reviews' %}> <i class="fas fa-arrow-right"></i> reviews </a>
                <a href={% url 'home:contact' %}> <i class="fas fa-arrow-right"></i> contact </a>
            </div>

            <div class="box">
                <h3>our branches</h3>
                <a href="#"> <i class="fas fa-map-marker-alt"></i> Viet Nam </a>
            </div>

            <div class="box">
                <h3>contact info</h3>
                <a href="#"> <i class="fab fa-facebook-f"></i> facebook </a>
                <a href="#"> <i class="fab fa-pinterest"></i> zalo </a>
                <a href="#"> <i class="fab fa-twitter"></i> twitter </a>
                <a href="#"> <i class="fab fa-instagram"></i> instagram </a>
            </div>

            <div class="box">
                <h3>contact info</h3>
                <a href="#"> <i class="fas fa-phone"></i> 0383508975 </a>
                <a href="#"> <i class="fas fa-envelope"></i> minhhh2004110025@student.giadinh.edu.vn </a>
                <a href="#"> <i class="fas fa-map-marker-alt"></i> Ho Chi Minh City </a>
            </div>

        </div>

        <div class="credit"> created by Huynh Huu Minh | K14DCPM01 | MSSV: 2004110025 </div>

    </section>

    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

    <script src="{% static 'js/script.js' %}"></script>  

</body>

</html>

home/templates/home/battery.html
{% extends 'home/base.html' %} 

{% block title %}Battery Replacement{% endblock %} 

{% block content %}
    {% load static %}
    <div class='wrapper'>
        <h1 class='title'>Bí quyết đổi mới năng lượng cho thiết bị của bạn</h1>
        <p class='desc'>
            Pin là nguồn năng lượng quan trọng cho các thiết bị di động như điện thoại di động, máy tính xách tay, máy nghe nhạc, đồng hồ, và nhiều thiết bị khác.
            <br/>
            <br/>
            Tuy nhiên, pin không thể hoạt động mãi mãi và sẽ cần thay thế sau một thời gian sử dụng.
            <br/>
            <br/>
            Trong nội dung này, chúng ta sẽ tìm hiểu về quá trình thay pin, các bước cần thiết và một số lưu ý quan trọng để đảm bảo thay pin thành công.
            <br/>
            <br/>
            1. Khi nào cần thay pin?
            <br/>
            Thời lượng pin ngắn: Nếu pin không còn đủ sức để duy trì hoạt động của thiết bị trong thời gian dài, đó có thể là dấu hiệu cần thay pin.
            <br />
            Sạc không đầy: Nếu pin không thể sạc đầy hoặc không thể giữ điện lâu sau khi đã sạc, điều này có thể chỉ ra rằng pin đã hỏng.
            <br />
            Các vấn đề kỹ thuật: Nếu thiết bị của bạn bị tắt ngấm do vấn đề pin, không khởi động được hoặc có các vấn đề hoạt động khác, việc thay pin có thể giải quyết vấn đề này.
            <br/>
            <br/>
            2. Các bước thay pin
            <br/>
            a. Tìm hiểu về loại pin: Xác định loại pin cần thiết cho thiết bị của bạn, bao gồm loại, kích thước và dung lượng.
            <br />
            b. Đảm bảo an toàn: Tắt thiết bị và ngắt kết nối với nguồn điện trước khi thay pin để tránh nguy cơ bị điện giật.
            <br />
            c. Mở nắp hoặc vỏ thiết bị: Theo hướng dẫn của nhà sản xuất hoặc sử dụng các công cụ phù hợp để mở nắp hoặc vỏ thiết bị.
            <br />
            d. Tháo pin cũ: Làm theo hướng dẫn và cẩn thận tháo pin cũ ra khỏi thiết bị.
            <br />
            e. Lắp pin mới: Chắc chắn đặt pin mới vào vị trí chính xác, đảm bảo cực dương và cực âm khớp với các khe tương ứng.
            <br />
            f. Đóng nắp hoặc vỏ thiết bị: Đảm bảo đóng kín nắp hoặc vỏ thiết
        </p>
    
    </div>{% endblock %}

home/templates/home/car_insurance.html
{% extends 'home/base.html' %} 

{% block title %}Car Insurance{% endblock %} 

{% block content %}
    {% load static %}
    <div class='wrapper'>
        <h1 class='title'>Bảo hiểm xe ô tô: Bảo vệ toàn diện cho chiếc xe của bạn</h1>
        <p class='desc'>
            Khi sở hữu một chiếc xe ô tô, việc có một chính sách bảo hiểm xe ô tô là rất quan trọng. 
            <br/>
            <br/>
            Bảo hiểm xe ô tô không chỉ bảo vệ bạn khỏi rủi ro tài chính liên quan đến xe của mình, mà còn mang lại sự an tâm và yên tâm khi tham gia giao thông.
            <br/>
            <br/>
            Trong nội dung này, chúng ta sẽ tìm hiểu về bảo hiểm xe ô tô, các loại bảo hiểm phổ biến, và những lợi ích mà nó mang lại.
            <br/>
            <br/>
            1. Bảo hiểm xe ô tô là gì?
            <br/>
            - Bảo hiểm xe ô tô là một hợp đồng giữa chủ xe và công ty bảo hiểm, trong đó công ty bảo hiểm cam kết bồi thường cho chủ xe trong trường hợp xe bị hư hỏng, mất mát hoặc gây ra thiệt hại cho bên thứ ba.
            <br/>
            <br/>
            2. Các loại bảo hiểm xe ô tô phổ biến
            <br/>
            - Bảo hiểm tổn thất
            - Bảo hiểm tai nạn
            - Bảo hiểm trách nhiệm dân sự
        </p>
    
    </div>{% endblock %}

home/templates/home/car_selling.html
{% extends 'home/base.html' %} 

{% block title %}Car Selling{% endblock %} 

{% block content %}
    {% load static %}
    <div class='wrapper'>
        <h1 class='title'>Khám phá Bộ sưu tập xe đẳng cấp của chúng tôi!</h1>
        <p class='desc'>
            Chào mừng bạn đến với chúng tôi, đại lý bán xe uy tín, nơi bạn có thể tìm thấy những chiếc xe đẳng cấp và đáng mơ ước. Chúng tôi tự hào được cung cấp dịch vụ bán xe hàng đầu, với một kho hàng đa dạng, đảm bảo đáp ứng nhu cầu của cả những khách hàng khó tính nhất.
            <br/>
            <br/>
            Chúng tôi không chỉ là một đại lý bán xe thông thường, mà còn là nơi bạn có thể tìm thấy sự tự tin và tiện nghi trong việc mua xe. Với nhiều năm kinh nghiệm trong ngành, chúng tôi đã xây dựng được một danh tiếng vững chắc dựa trên sự chuyên nghiệp và sự tận tâm với khách hàng.
            <br/>
            <br/>
            Khi khám phá bộ sưu tập xe của chúng tôi, bạn sẽ được trải nghiệm những mẫu xe vượt trội với các ưu điểm và tính năng nổi bật. Từ các dòng xe sang trọng và lịch lãm đến các mẫu xe thể thao đầy mê hoặc, chúng tôi cam kết mang đến sự đa dạng và lựa chọn tối ưu cho bạn.
            <br/>
            <br/>
            Hiệu suất mạnh mẽ, tiết kiệm nhiên liệu, công nghệ tiên tiến, an toàn cao và thiết kế đẹp mắt là những yếu tố chúng tôi luôn chú trọng trong việc chọn lựa các mẫu xe. Chúng tôi hiểu rằng việc mua một chiếc xe là một quyết định lớn, và chúng tôi cam kết chỉ mang đến những chiếc xe chất lượng cao nhất để đảm bảo sự hài lòng của khách hàng.
            <br/>
            <br/>
            Ngoài việc cung cấp những mẫu xe xuất sắc, chúng tôi còn coi trọng dịch vụ hậu mãi và sự chăm sóc sau khi mua xe. Đội ngũ nhân viên chuyên nghiệp và tận tâm của chúng tôi sẽ luôn sẵn lòng hỗ trợ bạn trong suốt quá trình sở hữu xe, đảm bảo rằng bạn luôn có trải nghiệm tuyệt vời với chiếc xe mới của mình.
            <br/>
            <br/>
            Để giúp bạn tiếp cận với chiếc xe mơ ước của mình, chúng tôi cung cấp các tùy chọn tài chính linh hoạt và gói vay hấp dẫn. Với sự tư vấn chuyên nghiệp từ đội ngũ tài chính của chúng tôi, chúng tôi sẽ giúp bạn tìm ra giải pháp tài chính phù hợp nhất với ngân sách và nhu cầu của bạn.
            <br/>
            <br/>
            Mỗi chiếc xe trong kho hàng của chúng tôi đã trải qua quy trình kiểm tra chất lượng nghiêm ngặt để đảm bảo sự tin cậy và an toàn cho khách hàng. Ngoài ra, chúng tôi cũng cung cấp các gói bảo hành đáng tin cậy, đảm bảo rằng bạn có sự yên tâm tuyệt đối khi lái xe.
            <br/>
            <br/>
            Đừng ngần ngại để lại phản hồi về trải nghiệm của bạn với chúng tôi. Chúng tôi luôn đánh giá cao ý kiến của khách hàng và sẽ sử dụng chúng để nâng cao dịch vụ của mình.
            <br/>
            <br/>
            Liên hệ với chúng tôi ngay hôm nay để khám phá bộ sưu tập xe đẳng cấp của chúng tôi và trải nghiệm sự phục vụ tuyệt vời của chúng tôi. Chúng tôi rất mong được hỗ trợ bạn trong việc tìm kiếm chiếc xe hoàn hảo cho nhu cầu của bạn!
        </p>
    
    </div>{% endblock %}

home/templates/home/home1.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop Car Sports - {% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" type="text/css">

</head>

<body>

    <header class="header">

        <div id="menu-btn" class="fas fa-bars"></div>

        <a href="#" class="logo"> <span>max</span>wheels </a>

        <nav class="navbar">
            <a href={% url 'home:home' %}>home</a>
            <a href={% url 'home:vehicles' %}>vehicles</a>
            <a href={% url 'home:services' %}>services</a>
            <a href={% url 'home:featured' %}>featured</a>
            <a href={% url 'home:reviews' %}>reviews</a>
            <a href={% url 'home:contact' %}>contact</a>
        </nav>

        <div id="login-btn">
            {% if user.is_authenticated %}
                <p>Welcome, {{ user.username }}!</p>
                <a href="{% url 'home:home' %}">Logout</a>
            {% else %}
            <a href={% url 'home:login' %} class="btn">login</a>
            {% endif %}
            <i class="far fa-user"></i>
        </div>

    </header>

    <div class="login-form-container-none">

        <span id="close-login-form" class="fas fa-times"></span>

        <form action="">
            <h3>user login</h3>
            <input type="email" placeholder="email" class="box">
            <input type="password" placeholder="password" class="box">
            <p> forget your password <a href="#">click here</a> </p>
            <input type="submit" value="login" class="btn">
            <p>or login with</p>
            <div class="buttons">
                <a href="#" class="btn"> google </a>
                <a href="#" class="btn"> facebook </a>
            </div>
            <p> don't have an account <a href="#">create one</a> </p>
        </form>

    </div>

    <section class="home" id="home">

        <h3 data-speed="-2" class="home-parallax">find your car</h3>

        <img data-speed="5" class="home-parallax" src="{% static 'images/home-img.png' %}" alt="">

        <a data-speed="7" href="#" class="btn home-parallax">explore cars</a>

    </section>

    <section class="icons-container">

        <div class="icons">
            <i class="fas fa-home"></i>
            <div class="content">
                <h3>150+</h3>
                <p>branches</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-car"></i>
            <div class="content">
                <h3>4770+</h3>
                <p>cars sold</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-users"></i>
            <div class="content">
                <h3>320+</h3>
                <p>happy clients</p>
            </div>
        </div>

        <div class="icons">
            <i class="fas fa-car"></i>
            <div class="content">
                <h3>1500+</h3>
                <p>news cars</p>
            </div>
        </div>

    </section>

    {% block content %}{% endblock %}

    <section class="footer" id="footer">

        <div class="box-container">

            <div class="box">
                <h3>quick links</h3>
                <a href={% url 'home:home' %}> <i class="fas fa-arrow-right"></i> home </a>
                <a href={% url 'home:vehicles' %}> <i class="fas fa-arrow-right"></i> vehicles </a>
                <a href={% url 'home:services' %}> <i class="fas fa-arrow-right"></i> services </a>
                <a href={% url 'home:featured' %}> <i class="fas fa-arrow-right"></i> featured </a>
                <a href={% url 'home:reviews' %}> <i class="fas fa-arrow-right"></i> reviews </a>
                <a href={% url 'home:contact' %}> <i class="fas fa-arrow-right"></i> contact </a>
            </div>

            <div class="box">
                <h3>our branches</h3>
                <a href="#"> <i class="fas fa-map-marker-alt"></i> Viet Nam </a>
            </div>

            <div class="box">
                <h3>contact info</h3>
                <a href="#"> <i class="fab fa-facebook-f"></i> facebook </a>
                <a href="#"> <i class="fab fa-pinterest"></i> zalo </a>
                <a href="#"> <i class="fab fa-twitter"></i> twitter </a>
                <a href="#"> <i class="fab fa-instagram"></i> instagram </a>
            </div>

            <div class="box">
                <h3>contact info</h3>
                <a href="#"> <i class="fas fa-phone"></i> 0383508975 </a>
                <a href="#"> <i class="fas fa-envelope"></i> minhhh2004110025@student.giadinh.edu.vn </a>
                <a href="#"> <i class="fas fa-map-marker-alt"></i> Ho Chi Minh City </a>
            </div>

        </div>

        <div class="credit"> created by Huynh Huu Minh | K14DCPM01 | MSSV: 2004110025 </div>

    </section>

    <script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

    <script src="{% static 'js/script.js' %}"></script>  

</body>

</html>

home/templates/home/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop Car Sports - Login</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" type="text/css">

</head>

<body>

    <div class="login-form-container">

        <a href={% url 'home:home' %} id="close-login-form" class="fas fa-times"></a>

        <form action="{% url 'home:login' %}" method="POST">
            <h3>user login</h3>
            {% csrf_token %}
            {{lG.as_p}}
            <input class='btn' type="Submit" value='Login'>
            <p>
                Don't have an account ? <a href={% url 'home:register' %}>Register</a>
            </p>
        </form>
    </div>

</body>

</html>

home/templates/home/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop Car Sports - Register</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" type="text/css">

</head>

<body>

    <div class="login-form-container">

        <a href={% url 'home:home' %} id="close-login-form" class="fas fa-times"></a>

        <form action="{% url 'home:register' %}" method="POST">
            <h3>user register</h3>
            {% csrf_token %}
            {{rG.as_p}}
            <input class='btn' type="Submit" value='Register'>
            <p>
                Already have an account ? <a href={% url 'home:login' %}>Login</a>
            </p>
        </form>

        {% comment %} <form action="">
            
        </form> {% endcomment %}

    </div>

</body>

</html>

home/templates/home/repair.html
{% extends 'home/base.html' %} 

{% block title %}Parts Repair{% endblock %} 

{% block content %}
    {% load static %}
    <div class='wrapper'>
        <h1 class='title'>Hướng dẫn Toàn diện về Sửa chữa Phụ tùng: Mọi thứ Bạn Cần Biết.</h1>
        <p class='desc'>
            Khi đến việc bảo dưỡng và sửa chữa các thiết bị và trang thiết bị khác nhau, hiểu rõ cơ bản về sửa chữa các bộ phận là rất quan trọng.
            <br/>
            <br/>
            Dù bạn là người đam mê làm việc DIY hay kỹ thuật viên chuyên nghiệp, có kiến thức và kỹ năng để sửa chữa từng thành phần riêng lẻ có thể giúp bạn tiết kiệm thời gian và tiền bạc.
            <br/>
            <br/>
            Trong hướng dẫn chi tiết này, chúng ta sẽ khám phá thế giới của sửa chữa các bộ phận, bao gồm các loại sửa chữa khác nhau, công cụ và kỹ thuật phổ biến, và những yếu tố quan trọng để đạt được sửa chữa thành công.
            <br/>
            <br/>
            Hãy cùng khám phá!
            <br/>
            <br/>
            1. Hiểu về sửa chữa các bộ phận.
            <br/>
            2. Lợi ích của việc sửa chữa các bộ phận.
            <br/>
            3. Các loại sửa chữa phổ biến.
            <br/>
        </p>
    
    </div>{% endblock %}

home/templates/home/services.html
{% extends 'home/base.html' %} 

{% block title %}Services{% endblock %} 

{% block content %}

{% load static %}

<section class="services" id="services">
  <h1 class="heading">our <span>services</span></h1>

  <div class="box-container">
    <div class="box">
      <i class="fas fa-car"></i>
      <h3>car selling</h3>
      <p>
        Khám phá Bộ sưu tập xe đẳng cấp của chúng tôi!
      </p>
      <a href={% url 'home:carselling' %} class="btn"> read more </a>
    </div>

    <div class="box">
      <i class="fas fa-tools"></i>
      <h3>parts repair</h3>
      <p>
        Hướng dẫn Toàn diện về Sửa chữa Phụ tùng: Mọi thứ Bạn Cần Biết.
      </p>
      <a href={% url 'home:repair' %} class="btn"> read more</a>
    </div>

    <div class="box">
      <i class="fas fa-car-crash"></i>
      <h3>car insurance</h3>
      <p>
        Bảo hiểm xe ô tô: Bảo vệ toàn diện cho chiếc xe của bạn
      </p>
      <a href={% url 'home:insurance' %} class="btn"> read more</a>
    </div>

    <div class="box">
      <i class="fas fa-car-battery"></i>
      <h3>battery replacement</h3>
      <p>
        Thay pin: Bí quyết đổi mới năng lượng cho thiết bị của bạn
      </p>
      <a href={% url 'home:battery' %} class="btn"> read more</a>
    </div>

    <div class="box">
      <i class="fas fa-gas-pump"></i>
      <h3>oil change</h3>
      <p>  
        Thay dầu động cơ: Bí quyết bảo vệ động cơ của bạn
      </p>
      <a href={% url 'home:oilchange' %} class="btn"> read more</a>
    </div>

    <div class="box">
      <i class="fas fa-headset"></i>
      <h3>24/7 support</h3>
      <p>
        Hỗ trợ 24/7: Luôn luôn đồng hành cùng bạn mọi lúc, mọi nơi
      </p>
      <a href={% url 'home:support' %} class="btn"> read more</a>
    </div>
  </div>
</section>

{% endblock %}